FROM node:18-alpine

ENV NODE_ENV=dev PYTHONUNBUFFERED=1 BUILD_APKS="python3 build-base git"

WORKDIR /opt/free-games-bot

# Python layer
RUN apk add --update --no-cache $BUILD_APKS \
    && ln -sf python3 /usr/bin/python \
    && python3 -m ensurepip \
    && pip3 install --no-cache --upgrade pip setuptools

# Npm layers
COPY package.json ./

RUN npm install -g gulp-cli typescript nodemon \
    && npm install

VOLUME /opt/free-games-bot

EXPOSE 9229

CMD ["npx", "nodemon", "src/index.ts"]